In [15]:
import numpy as np
a = np.random.randn(5)

print a

[-1.05886244 -2.39415191  2.09302581 -0.42640606  0.14210772]


In [16]:
print a.shape

(5,)


In [17]:
print a.T

[-1.05886244 -2.39415191  2.09302581 -0.42640606  0.14210772]


In [18]:
print np.dot(a,a.T)

11.4359268355


In [19]:
a = np.random.randn(5,1)
print a

[[-0.53209127]
 [-0.58916271]
 [-1.40495229]
 [-0.3492851 ]
 [ 0.07687331]]


In [20]:
print a.T

[[-0.53209127 -0.58916271 -1.40495229 -0.3492851   0.07687331]]


In [21]:
print np.dot(a, a.T)

[[ 0.28312112  0.31348833  0.74756284  0.18585155 -0.04090361]
 [ 0.31348833  0.3471127   0.82774549  0.20578575 -0.04529088]
 [ 0.74756284  0.82774549  1.97389092  0.49072889 -0.10800333]
 [ 0.18585155  0.20578575  0.49072889  0.12200008 -0.0268507 ]
 [-0.04090361 -0.04529088 -0.10800333 -0.0268507   0.00590951]]


In [22]:
print np.dot(a.T, a)

[[ 2.73203432]]


In [25]:
assert((5,) == (5,1))

AssertionError: 

In [27]:
assert((5,1) == (5,1))

In [28]:


c = np.random.randn(5)
print c

[ 0.35832002  0.16862992 -1.05077924 -0.19218351 -0.64853979]


In [29]:
c = c.reshape((5,1))
print c

[[ 0.35832002]
 [ 0.16862992]
 [-1.05077924]
 [-0.19218351]
 [-0.64853979]]
